variables:
    IMAGE_NAME: muhammadsziyad/docker-nodejs-fullstack-backend:v1

stages:
  - test
  - build
  - deploy

run_test:
  stage: test
  image: bitnami/node
  before_script:
    - npm install @babel/core @babel/preset-env @babel/register jest supertest express
  script:
    - npm test

build_images:
  stage: build
  image: docker
  services:
    - docker:27.2-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME


deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@202.10.41.81 "
        docker login -u $REGISTRY_USER -p $REGISTRY_PASS &&
        docker run -d -p 3000:3000 $IMAGE_NAME" 

#docker ps -aq | xargs docker stop | xargs docker rm &&
