variables:
    IMAGE_NAME: muhammadsziyad/docker-nodejs-fullstack-backend:v1

run_test:
  image: bitnami/node
  before_script:
    - npm install @babel/core @babel/preset-env @babel/register jest supertest express
  script:
    - npm test

build_images:
  image: docker
  services:
    - docker:27.2-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
